import { Server } from "../components/appstate";

const serverUrisList = (): Server[] => {
  return [
    // default servers (2)
    {
      uri: 'https://zec.rocks:443', // this will be the default server.
      region: 'USA' as string,
      chain_name: 'main',
      default: true,
      latency: null,
      obsolete: false,
    },
    {
      uri: 'https://lwd1.zcash-infra.com:9067',
      region: 'USA' as string,
      chain_name: 'main',
      default: true,
      latency: null,
      obsolete: false,
    },
    // new servers (not default) (11)
    {
      uri: 'https://na.zec.rocks:443',
      region: 'North America',
      chain_name: 'main',
      default: false,
      latency: null,
      obsolete: false,
    },
    {
      uri: 'https://sa.zec.rocks:443',
      region: 'South America',
      chain_name: 'main',
      default: false,
      latency: null,
      obsolete: false,
    },
    {
      uri: 'https://eu.zec.rocks:443',
      region: 'Europe & Africa',
      chain_name: 'main',
      default: false,
      latency: null,
      obsolete: false,
    },
    {
      uri: 'https://ap.zec.rocks:443',
      region: 'Asia & Oceania',
      chain_name: 'main',
      default: false,
      latency: null,
      obsolete: false,
    },
    {
      uri: 'https://lwd2.zcash-infra.com:9067',
      region: 'Hong Kong',
      chain_name: 'main',
      default: false,
      latency: null,
      obsolete: false,
    },
    {
      uri: 'https://lwd3.zcash-infra.com:9067',
      region: 'USA',
      chain_name: 'main',
      default: false,
      latency: null,
      obsolete: false,
    },
    {
      uri: 'https://lwd4.zcash-infra.com:9067',
      region: 'Canada',
      chain_name: 'main',
      default: false,
      latency: null,
      obsolete: false,
    },
    {
      uri: 'https://lwd5.zcash-infra.com:9067',
      region: 'France',
      chain_name: 'main',
      default: false,
      latency: null,
      obsolete: false,
    },
    {
      uri: 'https://lwd6.zcash-infra.com:9067',
      region: 'USA',
      chain_name: 'main',
      default: false,
      latency: null,
      obsolete: false,
    },
    {
      uri: 'https://lwd7.zcash-infra.com:9067',
      region: 'Netherlands',
      chain_name: 'main',
      default: false,
      latency: null,
      obsolete: false,
    },
    {
      uri: 'https://lwd8.zcash-infra.com:9067',
      region: 'UK',
      chain_name: 'main',
      default: false,
      latency: null,
      obsolete: false,
    },
    // obsolete servers (5)
    {
      uri: 'https://mainnet.lightwalletd.com:9067',
      region: 'North America',
      chain_name: 'main',
      default: true,
      latency: null,
      obsolete: true,
    },
    {
      uri: 'https://na.lightwalletd.com:443',
      region: 'North America',
      chain_name: 'main',
      default: false,
      latency: null,
      obsolete: true,
    },
    {
      uri: 'https://sa.lightwalletd.com:443',
      region: 'South America',
      chain_name: 'main',
      default: false,
      latency: null,
      obsolete: true,
    },
    {
      uri: 'https://eu.lightwalletd.com:443',
      region: 'Europe & Africa',
      chain_name: 'main',
      default: false,
      latency: null,
      obsolete: true,
    },
    {
      uri: 'https://ai.lightwalletd.com:443',
      region: 'Asia & Oceania',
      chain_name: 'main',
      default: false,
      latency: null,
      obsolete: true,
    },
  ];
};

export default serverUrisList;
